# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zLRDiCFgqDQjeAPLTgfJb2dqcCCzEjW2
"""

import csv
import os
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd


# =========================
# FUNCIONES ARCHIVOS CSV
# =========================

def guardarArchivo(nombreArchivo, listaDatos, campos):
    with open(nombreArchivo, mode='w', newline='', encoding='utf-8') as f:
        escritor = csv.DictWriter(f, fieldnames=campos)
        escritor.writeheader()
        escritor.writerows(listaDatos)


def cargarArchivo(nombreArchivo):
    if not os.path.exists(nombreArchivo):
        return []

    with open(nombreArchivo, mode='r', encoding='utf-8') as f:
        return list(csv.DictReader(f))


# =========================
# LÓGICA PRINCIPAL
# =========================

class LogicaIFN:

    def __init__(self):

        # Archivos
        self.archivoB = "brigadas.csv"
        self.archivoC = "conglomerados.csv"
        self.archivoFlora = "flora.csv"
        self.archivoFauna = "fauna.csv"

        # Campos
        self.camposB = [
            "idBrigada",
            "liderProfesional",
            "coinvestigadorLocal"
        ]

        self.camposC = [
            "idConglo",
            "latitud",
            "longitud",
            "idBrigada"
        ]

        self.camposFl = [
            "idSp",
            "idConglo",
            "nombreComun",
            "uso",
            "dap",
            "categoria"
        ]

        self.camposFa = [
            "idSp",
            "idConglo",
            "especie",
            "grupo",
            "estadoConservacion"
        ]

        # Cargar datos
        self.listaB = cargarArchivo(self.archivoB)
        self.listaC = cargarArchivo(self.archivoC)
        self.listaFl = cargarArchivo(self.archivoFlora)
        self.listaFa = cargarArchivo(self.archivoFauna)

    # =========================
    # ID AUTOINCREMENTAL
    # =========================

    def generarID(self, lista, prefijo):

        if not lista:
            return f"{prefijo}1"

        ultimo = lista[-1]

        clave = list(ultimo.keys())[0]

        numero = int(
            ultimo[clave].replace(prefijo, "")
        )

        return f"{prefijo}{numero + 1}"

    # =========================
    # CLASIFICAR DAP
    # =========================

    def clasificarDiametro(self, valorDap):

        d = float(valorDap)

        if 2.5 <= d <= 9.9:
            return "Brinzal"

        elif 10 <= d <= 29.9:
            return "Latizal"

        elif d >= 30:
            return "Fustal"

        return "No definido"

    # =========================
    # VALIDAR COORDENADAS
    # =========================

    def coordenadasValidas(self, lat, lon):

        return (
            0 <= lat <= 90 and
            0 <= lon <= 180
        )

    # =========================
    # BRIGADAS
    # =========================

    def agregarBrigada(self, lider, local):

        idB = self.generarID(
            self.listaB,
            "B"
        )

        self.listaB.append({
            "idBrigada": idB,
            "liderProfesional": lider,
            "coinvestigadorLocal": local
        })

        guardarArchivo(
            self.archivoB,
            self.listaB,
            self.camposB
        )

        return idB

    # =========================
    # CONGLOMERADOS
    # =========================

    def agregarConglomerado(
        self,
        lat,
        lon,
        idB
    ):

        if not self.coordenadasValidas(lat, lon):
            return None

        idC = self.generarID(
            self.listaC,
            "C"
        )

        self.listaC.append({
            "idConglo": idC,
            "latitud": lat,
            "longitud": lon,
            "idBrigada": idB
        })

        guardarArchivo(
            self.archivoC,
            self.listaC,
            self.camposC
        )

        return idC

    # =========================
    # FLORA
    # =========================

    def agregarFlora(
        self,
        idC,
        nom,
        uso,
        dap
    ):

        if dap <= 0:
            return None

        idS = self.generarID(
            self.listaFl,
            "FL"
        )

        categoria = self.clasificarDiametro(dap)

        self.listaFl.append({
            "idSp": idS,
            "idConglo": idC,
            "nombreComun": nom,
            "uso": uso,
            "dap": dap,
            "categoria": categoria
        })

        guardarArchivo(
            self.archivoFlora,
            self.listaFl,
            self.camposFl
        )

        return idS

    # =========================
    # FAUNA
    # =========================

    def agregarFauna(
        self,
        idC,
        esp,
        grp,
        est
    ):

        idS = self.generarID(
            self.listaFa,
            "FA"
        )

        self.listaFa.append({
            "idSp": idS,
            "idConglo": idC,
            "especie": esp,
            "grupo": grp,
            "estadoConservacion": est
        })

        guardarArchivo(
            self.archivoFauna,
            self.listaFa,
            self.camposFa
        )

        return idS


# =========================
# INSTANCIA
# =========================

logica = LogicaIFN()

salida = widgets.Output()


# =========================
# WIDGETS BRIGADAS
# =========================

txtLider = widgets.Text(
    description='Profesional:'
)

drpLocal = widgets.Dropdown(
    options=[
        'Comunidad indígena',
        'Campesino',
        'Guía local',
        'Auxiliar técnico'
    ],
    description='Local:'
)

btnB = widgets.Button(
    description='Registrar Brigada',
    button_style='primary'
)


# =========================
# WIDGETS CONGLOMERADOS
# =========================

numLat = widgets.FloatText(
    description='Latitud:'
)

numLon = widgets.FloatText(
    description='Longitud:'
)

drpB = widgets.Dropdown(
    description='Brigada:'
)

btnC = widgets.Button(
    description='Crear Conglomerado',
    button_style='success'
)


# =========================
# WIDGETS FLORA
# =========================

drpC_Fl = widgets.Dropdown(
    description='Conglo:'
)

txtNomFl = widgets.Text(
    description='Nombre:'
)

drpUsoFl = widgets.Dropdown(
    options=[
        'Medicinal',
        'Alimenticio',
        'Maderable'
    ],
    description='Uso:'
)

numDap = widgets.FloatText(
    description='DAP (cm):',
    value=2.5
)

btnFl = widgets.Button(
    description='Registrar Flora',
    button_style='success'
)


# =========================
# WIDGETS FAUNA
# =========================

drpC_Fa = widgets.Dropdown(
    description='Conglo:'
)

txtEspFa = widgets.Text(
    description='Especie:'
)

drpGrpFa = widgets.Dropdown(
    options=[
        'Aves',
        'Mamíferos',
        'Reptiles'
    ],
    description='Grupo:'
)

drpEstFa = widgets.Dropdown(
    options=[
        'Crítico',
        'Amenazado',
        'Vulnerable',
        'Sano'
    ],
    description='Estado:'
)

btnFa = widgets.Button(
    description='Registrar Fauna',
    button_style='warning'
)


# =========================
# ACTUALIZAR MENÚS
# =========================

def actualizarMenus():

    opcionesB = [
        b['idBrigada']
        for b in logica.listaB
    ]

    opcionesC = [
        c['idConglo']
        for c in logica.listaC
    ]

    drpB.options = opcionesB

    drpC_Fl.options = opcionesC

    drpC_Fa.options = opcionesC


# =========================
# EVENTOS BOTONES
# =========================

def alClickB(b):

    idB = logica.agregarBrigada(
        txtLider.value,
        drpLocal.value
    )

    actualizarMenus()

    txtLider.value = ""

    with salida:
        clear_output()
        print(f"Brigada {idB} registrada correctamente.")


def alClickC(b):

    idC = logica.agregarConglomerado(
        numLat.value,
        numLon.value,
        drpB.value
    )

    with salida:

        clear_output()

        if idC:
            print(f"Conglomerado {idC} creado.")

        else:
            print("ERROR: Coordenadas inválidas.")

    actualizarMenus()

    numLat.value = 0
    numLon.value = 0


def alClickFl(b):

    idFl = logica.agregarFlora(
        drpC_Fl.value,
        txtNomFl.value,
        drpUsoFl.value,
        numDap.value
    )

    with salida:

        clear_output()

        if idFl:
            print(f"Flora {idFl} registrada.")

        else:
            print("ERROR: DAP inválido.")

    txtNomFl.value = ""
    numDap.value = 2.5


def alClickFa(b):

    idFa = logica.agregarFauna(
        drpC_Fa.value,
        txtEspFa.value,
        drpGrpFa.value,
        drpEstFa.value
    )

    with salida:
        clear_output()
        print(f"Fauna {idFa} registrada.")

    txtEspFa.value = ""


# =========================
# BOTONES
# =========================

btnB.on_click(alClickB)
btnC.on_click(alClickC)
btnFl.on_click(alClickFl)
btnFa.on_click(alClickFa)


# =========================
# REPORTE
# =========================

btnReporte = widgets.Button(
    description='Ver Reporte Integral',
    button_style='info'
)


def alClickReporte(b):

    with salida:

        clear_output()

        print("=== REPORTE IFN ===")

        for c in logica.listaC:

            print("\n====================")

            print(
                f"CONGLOMERADO: {c['idConglo']}"
            )

            print(
                f"LATITUD: {c['latitud']}"
            )

            print(
                f"LONGITUD: {c['longitud']}"
            )

            flora = [
                f['nombreComun']
                for f in logica.listaFl
                if f['idConglo'] == c['idConglo']
            ]

            fauna = [
                a['especie']
                for a in logica.listaFa
                if a['idConglo'] == c['idConglo']
            ]

            print(
                f"Flora: {flora if flora else 'Sin registros'}"
            )

            print(
                f"Fauna: {fauna if fauna else 'Sin registros'}"
            )

        print("\n====================")

        print("\nTABLAS GENERALES")

        display(pd.DataFrame(logica.listaB))
        display(pd.DataFrame(logica.listaC))
        display(pd.DataFrame(logica.listaFl))
        display(pd.DataFrame(logica.listaFa))


btnReporte.on_click(alClickReporte)


# =========================
# ACTUALIZAR MENÚS
# =========================

actualizarMenus()


# =========================
# INTERFAZ
# =========================

tabs = widgets.Tab(children=[

    widgets.VBox([
        txtLider,
        drpLocal,
        btnB
    ]),

    widgets.VBox([
        numLat,
        numLon,
        drpB,
        btnC
    ]),

    widgets.VBox([
        drpC_Fl,
        txtNomFl,
        drpUsoFl,
        numDap,
        btnFl
    ]),

    widgets.VBox([
        drpC_Fa,
        txtEspFa,
        drpGrpFa,
        drpEstFa,
        btnFa
    ])

])

tabs.set_title(0, 'Brigadas')
tabs.set_title(1, 'Conglomerados')
tabs.set_title(2, 'Flora')
tabs.set_title(3, 'Fauna')


display(
    tabs,
    btnReporte,
    salida
)

import csv
import os
import pandas as pd
import ipywidgets as widgets

from IPython.display import display, clear_output


# =====================================================
# FUNCIONES CSV
# =====================================================

def guardarArchivo(nombreArchivo, listaDatos, campos):

    with open(
        nombreArchivo,
        mode='w',
        newline='',
        encoding='utf-8'
    ) as f:

        escritor = csv.DictWriter(
            f,
            fieldnames=campos
        )

        escritor.writeheader()

        escritor.writerows(listaDatos)


def cargarArchivo(nombreArchivo):

    if not os.path.exists(nombreArchivo):
        return []

    with open(
        nombreArchivo,
        mode='r',
        encoding='utf-8'
    ) as f:

        return list(csv.DictReader(f))


# =====================================================
# LÓGICA PRINCIPAL
# =====================================================

class LogicaIFN:

    def __init__(self):

        # -------------------------------
        # Archivos
        # -------------------------------

        self.archivoB = "brigadas.csv"
        self.archivoC = "conglomerados.csv"
        self.archivoFlora = "flora.csv"
        self.archivoFauna = "fauna.csv"

        # -------------------------------
        # Campos
        # -------------------------------

        self.camposB = [
            "idBrigada",
            "liderProfesional",
            "coinvestigadorLocal"
        ]

        self.camposC = [
            "idConglo",
            "latitud",
            "longitud",
            "idBrigada"
        ]

        self.camposFl = [
            "idSp",
            "idConglo",
            "nombreComun",
            "uso",
            "dap",
            "categoria"
        ]

        self.camposFa = [
            "idSp",
            "idConglo",
            "especie",
            "grupo",
            "estadoConservacion"
        ]

        # -------------------------------
        # Cargar datos
        # -------------------------------

        self.listaB = cargarArchivo(
            self.archivoB
        )

        self.listaC = cargarArchivo(
            self.archivoC
        )

        self.listaFl = cargarArchivo(
            self.archivoFlora
        )

        self.listaFa = cargarArchivo(
            self.archivoFauna
        )

    # =====================================================
    # GENERAR IDs
    # =====================================================

    def generarID(self, lista, prefijo):

        if not lista:
            return f"{prefijo}1"

        ultimo = lista[-1]

        clave = list(ultimo.keys())[0]

        numero = int(
            ultimo[clave].replace(prefijo, "")
        )

        return f"{prefijo}{numero + 1}"

    # =====================================================
    # CLASIFICAR DAP
    # =====================================================

    def clasificarDiametro(self, dap):

        d = float(dap)

        if 2.5 <= d <= 9.9:
            return "Brinzal"

        elif 10 <= d <= 29.9:
            return "Latizal"

        elif d >= 30:
            return "Fustal"

        return "No definido"

    # =====================================================
    # VALIDAR COORDENADAS
    # =====================================================

    def coordenadasValidas(
        self,
        lat,
        lon
    ):

        return (
            0 <= lat <= 90 and
            0 <= lon <= 180
        )

    # =====================================================
    # BRIGADAS
    # =====================================================

    def agregarBrigada(
        self,
        lider,
        local
    ):

        idB = self.generarID(
            self.listaB,
            "B"
        )

        self.listaB.append({

            "idBrigada": idB,

            "liderProfesional": lider,

            "coinvestigadorLocal": local
        })

        guardarArchivo(
            self.archivoB,
            self.listaB,
            self.camposB
        )

        return idB

    def editarBrigada(
        self,
        idB,
        nuevoLider,
        nuevoLocal
    ):

        for b in self.listaB:

            if b['idBrigada'] == idB:

                b['liderProfesional'] = nuevoLider

                b['coinvestigadorLocal'] = nuevoLocal

                guardarArchivo(
                    self.archivoB,
                    self.listaB,
                    self.camposB
                )

                return True

        return False

    def eliminarBrigada(
        self,
        idB
    ):

        self.listaB = [

            b for b in self.listaB

            if b['idBrigada'] != idB
        ]

        guardarArchivo(
            self.archivoB,
            self.listaB,
            self.camposB
        )

    # =====================================================
    # CONGLOMERADOS
    # =====================================================

    def agregarConglomerado(
        self,
        lat,
        lon,
        idB
    ):

        if not self.coordenadasValidas(
            lat,
            lon
        ):
            return None

        idC = self.generarID(
            self.listaC,
            "C"
        )

        self.listaC.append({

            "idConglo": idC,

            "latitud": lat,

            "longitud": lon,

            "idBrigada": idB
        })

        guardarArchivo(
            self.archivoC,
            self.listaC,
            self.camposC
        )

        return idC

    def editarConglomerado(
        self,
        idC,
        lat,
        lon,
        idB
    ):

        for c in self.listaC:

            if c['idConglo'] == idC:

                c['latitud'] = lat
                c['longitud'] = lon
                c['idBrigada'] = idB

                guardarArchivo(
                    self.archivoC,
                    self.listaC,
                    self.camposC
                )

                return True

        return False

    def eliminarConglomerado(
        self,
        idC
    ):

        self.listaC = [

            c for c in self.listaC

            if c['idConglo'] != idC
        ]

        guardarArchivo(
            self.archivoC,
            self.listaC,
            self.camposC
        )

    # =====================================================
    # FLORA
    # =====================================================

    def agregarFlora(
        self,
        idC,
        nom,
        uso,
        dap
    ):

        if dap <= 0:
            return None

        idS = self.generarID(
            self.listaFl,
            "FL"
        )

        categoria = self.clasificarDiametro(
            dap
        )

        self.listaFl.append({

            "idSp": idS,

            "idConglo": idC,

            "nombreComun": nom,

            "uso": uso,

            "dap": dap,

            "categoria": categoria
        })

        guardarArchivo(
            self.archivoFlora,
            self.listaFl,
            self.camposFl
        )

        return idS

    def editarFlora(
        self,
        idS,
        nombre,
        uso,
        dap
    ):

        for f in self.listaFl:

            if f['idSp'] == idS:

                f['nombreComun'] = nombre
                f['uso'] = uso
                f['dap'] = dap

                f['categoria'] = self.clasificarDiametro(
                    dap
                )

                guardarArchivo(
                    self.archivoFlora,
                    self.listaFl,
                    self.camposFl
                )

                return True

        return False

    def eliminarFlora(
        self,
        idS
    ):

        self.listaFl = [

            f for f in self.listaFl

            if f['idSp'] != idS
        ]

        guardarArchivo(
            self.archivoFlora,
            self.listaFl,
            self.camposFl
        )

    # =====================================================
    # FAUNA
    # =====================================================

    def agregarFauna(
        self,
        idC,
        esp,
        grp,
        est
    ):

        idS = self.generarID(
            self.listaFa,
            "FA"
        )

        self.listaFa.append({

            "idSp": idS,

            "idConglo": idC,

            "especie": esp,

            "grupo": grp,

            "estadoConservacion": est
        })

        guardarArchivo(
            self.archivoFauna,
            self.listaFa,
            self.camposFa
        )

        return idS

    def editarFauna(
        self,
        idS,
        especie,
        grupo,
        estado
    ):

        for a in self.listaFa:

            if a['idSp'] == idS:

                a['especie'] = especie
                a['grupo'] = grupo
                a['estadoConservacion'] = estado

                guardarArchivo(
                    self.archivoFauna,
                    self.listaFa,
                    self.camposFa
                )

                return True

        return False

    def eliminarFauna(
        self,
        idS
    ):

        self.listaFa = [

            a for a in self.listaFa

            if a['idSp'] != idS
        ]

        guardarArchivo(
            self.archivoFauna,
            self.listaFa,
            self.camposFa
        )


# =====================================================
# INSTANCIA
# =====================================================

logica = LogicaIFN()

salida = widgets.Output()


# =====================================================
# BRIGADAS
# =====================================================

drpEditarB = widgets.Dropdown(
    description='Brigada:'
)

txtLider = widgets.Text(
    description='Profesional:'
)

drpLocal = widgets.Dropdown(

    options=[
        'Comunidad indígena',
        'Campesino',
        'Guía local',
        'Auxiliar técnico'
    ],

    description='Local:'
)

btnB = widgets.Button(
    description='Registrar',
    button_style='success'
)

btnEditarB = widgets.Button(
    description='Editar',
    button_style='warning'
)

btnEliminarB = widgets.Button(
    description='Eliminar',
    button_style='danger'
)


# =====================================================
# CONGLOMERADOS
# =====================================================

drpEditarC = widgets.Dropdown(
    description='Conglo:'
)

numLat = widgets.FloatText(
    description='Latitud:'
)

numLon = widgets.FloatText(
    description='Longitud:'
)

drpB = widgets.Dropdown(
    description='Brigada:'
)

btnC = widgets.Button(
    description='Registrar',
    button_style='success'
)

btnEditarC = widgets.Button(
    description='Editar',
    button_style='warning'
)

btnEliminarC = widgets.Button(
    description='Eliminar',
    button_style='danger'
)


# =====================================================
# FLORA
# =====================================================

drpEditarFl = widgets.Dropdown(
    description='Flora:'
)

drpC_Fl = widgets.Dropdown(
    description='Conglo:'
)

txtNomFl = widgets.Text(
    description='Nombre:'
)

drpUsoFl = widgets.Dropdown(

    options=[
        'Medicinal',
        'Alimenticio',
        'Maderable'
    ],

    description='Uso:'
)

numDap = widgets.FloatText(
    description='DAP:',
    value=2.5
)

btnFl = widgets.Button(
    description='Registrar',
    button_style='success'
)

btnEditarFl = widgets.Button(
    description='Editar',
    button_style='warning'
)

btnEliminarFl = widgets.Button(
    description='Eliminar',
    button_style='danger'
)


# =====================================================
# FAUNA
# =====================================================

drpEditarFa = widgets.Dropdown(
    description='Fauna:'
)

drpC_Fa = widgets.Dropdown(
    description='Conglo:'
)

txtEspFa = widgets.Text(
    description='Especie:'
)

drpGrpFa = widgets.Dropdown(

    options=[
        'Aves',
        'Mamíferos',
        'Reptiles'
    ],

    description='Grupo:'
)

drpEstFa = widgets.Dropdown(

    options=[
        'Crítico',
        'Amenazado',
        'Vulnerable',
        'Sano'
    ],

    description='Estado:'
)

btnFa = widgets.Button(
    description='Registrar',
    button_style='success'
)

btnEditarFa = widgets.Button(
    description='Editar',
    button_style='warning'
)

btnEliminarFa = widgets.Button(
    description='Eliminar',
    button_style='danger'
)


# =====================================================
# ACTUALIZAR MENÚS
# =====================================================

def actualizarMenus():

    opcionesB = [
        b['idBrigada']
        for b in logica.listaB
    ]

    opcionesC = [
        c['idConglo']
        for c in logica.listaC
    ]

    opcionesFl = [
        f['idSp']
        for f in logica.listaFl
    ]

    opcionesFa = [
        a['idSp']
        for a in logica.listaFa
    ]

    drpEditarB.options = opcionesB
    drpB.options = opcionesB

    drpEditarC.options = opcionesC

    drpC_Fl.options = opcionesC
    drpC_Fa.options = opcionesC

    drpEditarFl.options = opcionesFl

    drpEditarFa.options = opcionesFa


# =====================================================
# CARGAR DATOS AUTOMÁTICAMENTE
# =====================================================

def cargarBrigada(change):

    for b in logica.listaB:

        if b['idBrigada'] == change['new']:

            txtLider.value = b['liderProfesional']
            drpLocal.value = b['coinvestigadorLocal']


def cargarConglo(change):

    for c in logica.listaC:

        if c['idConglo'] == change['new']:

            numLat.value = float(c['latitud'])
            numLon.value = float(c['longitud'])
            drpB.value = c['idBrigada']


def cargarFlora(change):

    for f in logica.listaFl:

        if f['idSp'] == change['new']:

            drpC_Fl.value = f['idConglo']
            txtNomFl.value = f['nombreComun']
            drpUsoFl.value = f['uso']
            numDap.value = float(f['dap'])


def cargarFauna(change):

    for a in logica.listaFa:

        if a['idSp'] == change['new']:

            drpC_Fa.value = a['idConglo']
            txtEspFa.value = a['especie']
            drpGrpFa.value = a['grupo']
            drpEstFa.value = a['estadoConservacion']


drpEditarB.observe(cargarBrigada, names='value')
drpEditarC.observe(cargarConglo, names='value')
drpEditarFl.observe(cargarFlora, names='value')
drpEditarFa.observe(cargarFauna, names='value')


# =====================================================
# EVENTOS BRIGADAS
# =====================================================

def clickRegistrarB(b):

    idB = logica.agregarBrigada(
        txtLider.value,
        drpLocal.value
    )

    actualizarMenus()

    with salida:

        clear_output()

        print(f"Brigada {idB} registrada.")


def clickEditarB(b):

    ok = logica.editarBrigada(
        drpEditarB.value,
        txtLider.value,
        drpLocal.value
    )

    with salida:

        clear_output()

        print(
            "Brigada editada."
            if ok else
            "Error."
        )


def clickEliminarB(b):

    logica.eliminarBrigada(
        drpEditarB.value
    )

    actualizarMenus()

    with salida:

        clear_output()

        print("Brigada eliminada.")


# =====================================================
# EVENTOS CONGLOMERADOS
# =====================================================

def clickRegistrarC(b):

    idC = logica.agregarConglomerado(
        numLat.value,
        numLon.value,
        drpB.value
    )

    actualizarMenus()

    with salida:

        clear_output()

        if idC:

            print(f"Conglomerado {idC} registrado.")

        else:

            print("Coordenadas inválidas.")


def clickEditarC(b):

    ok = logica.editarConglomerado(
        drpEditarC.value,
        numLat.value,
        numLon.value,
        drpB.value
    )

    with salida:

        clear_output()

        print(
            "Conglomerado editado."
            if ok else
            "Error."
        )


def clickEliminarC(b):

    logica.eliminarConglomerado(
        drpEditarC.value
    )

    actualizarMenus()

    with salida:

        clear_output()

        print("Conglomerado eliminado.")


# =====================================================
# EVENTOS FLORA
# =====================================================

def clickRegistrarFl(b):

    idFl = logica.agregarFlora(
        drpC_Fl.value,
        txtNomFl.value,
        drpUsoFl.value,
        numDap.value
    )

    actualizarMenus()

    with salida:

        clear_output()

        print(
            f"Flora {idFl} registrada."
            if idFl else
            "DAP inválido."
        )


def clickEditarFl(b):

    ok = logica.editarFlora(
        drpEditarFl.value,
        txtNomFl.value,
        drpUsoFl.value,
        numDap.value
    )

    with salida:

        clear_output()

        print(
            "Flora editada."
            if ok else
            "Error."
        )


def clickEliminarFl(b):

    logica.eliminarFlora(
        drpEditarFl.value
    )

    actualizarMenus()

    with salida:

        clear_output()

        print("Flora eliminada.")


# =====================================================
# EVENTOS FAUNA
# =====================================================

def clickRegistrarFa(b):

    idFa = logica.agregarFauna(
        drpC_Fa.value,
        txtEspFa.value,
        drpGrpFa.value,
        drpEstFa.value
    )

    actualizarMenus()

    with salida:

        clear_output()

        print(f"Fauna {idFa} registrada.")


def clickEditarFa(b):

    ok = logica.editarFauna(
        drpEditarFa.value,
        txtEspFa.value,
        drpGrpFa.value,
        drpEstFa.value
    )

    with salida:

        clear_output()

        print(
            "Fauna editada."
            if ok else
            "Error."
        )


def clickEliminarFa(b):

    logica.eliminarFauna(
        drpEditarFa.value
    )

    actualizarMenus()

    with salida:

        clear_output()

        print("Fauna eliminada.")


# =====================================================
# CONECTAR BOTONES
# =====================================================

btnB.on_click(clickRegistrarB)
btnEditarB.on_click(clickEditarB)
btnEliminarB.on_click(clickEliminarB)

btnC.on_click(clickRegistrarC)
btnEditarC.on_click(clickEditarC)
btnEliminarC.on_click(clickEliminarC)

btnFl.on_click(clickRegistrarFl)
btnEditarFl.on_click(clickEditarFl)
btnEliminarFl.on_click(clickEliminarFl)

btnFa.on_click(clickRegistrarFa)
btnEditarFa.on_click(clickEditarFa)
btnEliminarFa.on_click(clickEliminarFa)


# =====================================================
# REPORTE
# =====================================================

btnReporte = widgets.Button(
    description='Ver Reporte',
    button_style='info'
)


def clickReporte(b):

    with salida:

        clear_output()

        print("========== REPORTE ==========")

        print("\nBRIGADAS")
        display(pd.DataFrame(logica.listaB))

        print("\nCONGLOMERADOS")
        display(pd.DataFrame(logica.listaC))

        print("\nFLORA")
        display(pd.DataFrame(logica.listaFl))

        print("\nFAUNA")
        display(pd.DataFrame(logica.listaFa))


btnReporte.on_click(clickReporte)


# =====================================================
# ACTUALIZAR MENÚS
# =====================================================

actualizarMenus()


# =====================================================
# INTERFAZ
# =====================================================

tabs = widgets.Tab(children=[

    widgets.VBox([

        drpEditarB,

        txtLider,

        drpLocal,

        btnB,

        btnEditarB,

        btnEliminarB
    ]),

    widgets.VBox([

        drpEditarC,

        numLat,

        numLon,

        drpB,

        btnC,

        btnEditarC,

        btnEliminarC
    ]),

    widgets.VBox([

        drpEditarFl,

        drpC_Fl,

        txtNomFl,

        drpUsoFl,

        numDap,

        btnFl,

        btnEditarFl,

        btnEliminarFl
    ]),

    widgets.VBox([

        drpEditarFa,

        drpC_Fa,

        txtEspFa,

        drpGrpFa,

        drpEstFa,

        btnFa,

        btnEditarFa,

        btnEliminarFa
    ])
])

tabs.set_title(0, 'Brigadas')
tabs.set_title(1, 'Conglomerados')
tabs.set_title(2, 'Flora')
tabs.set_title(3, 'Fauna')


display(
    tabs,
    btnReporte,
    salida
)