# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRSNm59_47TZWImjq2uk1C35nE39g18u
"""

import csv
import os
import ipywidgets as widgets
from IPython.display import display, clear_output
from google.colab import files



def guardarArchivo(nombreArchivo, listaDatos, campos):
    with open(nombreArchivo, mode='w', newline='', encoding='utf-8') as f:
        escritor = csv.DictWriter(f, fieldnames=campos)
        escritor.writeheader()
        escritor.writerows(listaDatos)

def cargarArchivo(nombreArchivo):
    if not os.path.exists(nombreArchivo): return []
    with open(nombreArchivo, mode='r', encoding='utf-8') as f:
        return list(csv.DictReader(f))



class LogicaIFN:
    def __init__(self):
        self.archivoB = "brigadas.csv"
        self.archivoC = "conglomerados.csv"
        self.archivoFlora = "flora.csv"
        self.archivoFauna = "fauna.csv"

        self.camposB = ["idBrigada", "liderProfesional", "coinvestigadorLocal"]
        self.camposC = ["idConglo", "coordenadasGPS", "idBrigada"]
        self.camposFl = ["idSp", "idConglo", "nombreComun", "uso", "dap", "categoria"]
        self.camposFa = ["idSp", "idConglo", "especie", "grupo", "estadoConservacion"]

        self.listaB = cargarArchivo(self.archivoB)
        self.listaC = cargarArchivo(self.archivoC)
        self.listaFl = cargarArchivo(self.archivoFlora)
        self.listaFa = cargarArchivo(self.archivoFauna)

    def clasificarDiametro(self, valorDap):
        """Clasificación técnica: Brinzales (2.5-9.9), Latizales (10-29.9) y Fustales (>=30) [5], [6]."""
        d = float(valorDap)
        if 2.5 <= d <= 9.9: return "Brinzal"
        elif 10.0 <= d <= 29.9: return "Latizal"
        elif d >= 30.0: return "Fustal"
        return "No definido"

    def agregarBrigada(self, idB, lider, local):
        self.listaB.append({"idBrigada": idB, "liderProfesional": lider, "coinvestigadorLocal": local})
        guardarArchivo(self.archivoB, self.listaB, self.camposB)

    def agregarConglomerado(self, idC, gps, idB):
        self.listaC.append({"idConglo": idC, "coordenadasGPS": gps, "idBrigada": idB})
        guardarArchivo(self.archivoC, self.listaC, self.camposC)

    def agregarFlora(self, idS, idC, nom, uso, dap):
        cat = self.clasificarDiametro(dap)
        self.listaFl.append({"idSp": idS, "idConglo": idC, "nombreComun": nom, "uso": uso, "dap": dap, "categoria": cat})
        guardarArchivo(self.archivoFlora, self.listaFl, self.camposFl)

    def agregarFauna(self, idS, idC, esp, grp, est):
        self.listaFa.append({"idSp": idS, "idConglo": idC, "especie": esp, "grupo": grp, "estadoConservacion": est})
        guardarArchivo(self.archivoFauna, self.listaFa, self.camposFa)


logica = LogicaIFN()
salida = widgets.Output()


txtIdB = widgets.Text(description='ID Brigada:')
txtLider = widgets.Text(description='Profesional:')
txtLocal = widgets.Text(description='Local:')
btnB = widgets.Button(description='Registrar Brigada', button_style='primary')


txtIdC = widgets.Text(description='ID Conglo:')
txtGPS = widgets.Text(description='Coordenadas:', placeholder='Lat, Long')
drpB = widgets.Dropdown(description='Brigada:')
btnC = widgets.Button(description='Crear Conglo.', button_style='success')


txtIdFl = widgets.Text(description='ID Muestra:')
drpC_Fl = widgets.Dropdown(description='Conglo:')
txtNomFl = widgets.Text(description='Nombre:')
drpUsoFl = widgets.Dropdown(options=['Medicinal', 'Alimenticio', 'Maderable'], description='Uso:')
numDap = widgets.FloatText(description='DAP (cm):', value=2.5)
btnFl = widgets.Button(description='Registrar Flora', button_style='success')

txtIdFa = widgets.Text(description='ID Muestra:')
drpC_Fa = widgets.Dropdown(description='Conglo:')
txtEspFa = widgets.Text(description='Especie:', placeholder='Ej: Paujil pico azul')
drpGrpFa = widgets.Dropdown(options=['Aves', 'Mamíferos', 'Reptiles'], description='Grupo:')
drpEstFa = widgets.Dropdown(options=['Crítico', 'Amenazado', 'Vulnerable', 'Sano'], description='Estado:')
btnFa = widgets.Button(description='Registrar Fauna', button_style='warning')

def actualizarMenus():
    opcionesB = [b['idBrigada'] for b in logica.listaB]
    opcionesC = [c['idConglo'] for c in logica.listaC]
    drpB.options = opcionesB
    drpC_Fl.options = opcionesC
    drpC_Fa.options = opcionesC

def alClickB(b):
    logica.agregarBrigada(txtIdB.value, txtLider.value, txtLocal.value)
    actualizarMenus()
    with salida: clear_output(); print(f"Brigada {txtIdB.value} registrada.")

def alClickC(b):
    logica.agregarConglomerado(txtIdC.value, txtGPS.value, drpB.value)
    actualizarMenus()
    with salida: clear_output(); print(f"Conglomerado {txtIdC.value} creado.")

def alClickFl(b):
    logica.agregarFlora(txtIdFl.value, drpC_Fl.value, txtNomFl.value, drpUsoFl.value, numDap.value)
    with salida: clear_output(); print(f"Flora {txtIdFl.value} registrada.")

def alClickFa(b):
    logica.agregarFauna(txtIdFa.value, drpC_Fa.value, txtEspFa.value, drpGrpFa.value, drpEstFa.value)
    with salida: clear_output(); print(f"Fauna {txtIdFa.value} registrada.")

btnB.on_click(alClickB); btnC.on_click(alClickC); btnFl.on_click(alClickFl); btnFa.on_click(alClickFa)


btnReporte = widgets.Button(description='Ver Reporte Integral', button_style='info')

def alClickReporte(b):
    with salida:
        clear_output()
        print("=== REPORTE DE INSPECCIÓN IFN ===")
        for c in logica.listaC:
            print(f"\nCONGLOMERADO: {c['idConglo']} | GPS: {c['gps']}")
            fl = [f['nombreComun'] for f in logica.listaFl if f['idConglo'] == c['idConglo']]
            fa = [a['especie'] for a in logica.listaFa if a['idConglo'] == c['idConglo']]
            print(f"  > Flora: {fl if fl else 'Sin registros'}")
            print(f"  > Fauna: {fa if fa else 'Sin registros'}")

btnReporte.on_click(alClickReporte)
actualizarMenus()


tabs = widgets.Tab(children=[
    widgets.VBox([txtIdB, txtLider, txtLocal, btnB]),
    widgets.VBox([txtIdC, txtGPS, drpB, btnC]),
    widgets.VBox([txtIdFl, drpC_Fl, txtNomFl, drpUsoFl, numDap, btnFl]),
    widgets.VBox([txtIdFa, drpC_Fa, txtEspFa, drpGrpFa, drpEstFa, btnFa])
])
tabs.set_title(0, 'Brigadas'); tabs.set_title(1, 'Conglomerados')
tabs.set_title(2, 'Flora'); tabs.set_title(3, 'Fauna')

display(tabs, btnReporte, salida)